name: Docker build CI

on: [push]

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Login to GitHub Package Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_TO_ACCESS_PACKAGE_REGISTRY }}
        run: docker login docker.pkg.github.com -u btk15049 -p $GITHUB_TOKEN
      #- name: Get image for cache from Github Package Registry
      #  env:
      #    CONTAINER_REGISTRY_PATH: docker.pkg.github.com/${{ github.repository }}
      #    IMAGE_NAME: ubuntu
      #  run: |
      #    docker pull ${CONTAINER_REGISTRY_PATH}/${IMAGE_NAME}:latest
      #    docker tag ${CONTAINER_REGISTRY_PATH}/${IMAGE_NAME}:latest cache
      - name: Build docker image
        run: |
      #    docker build --cache-from cache -t current .
          docker build -t current .
      - name: Push docker image
        env:
          CONTAINER_REGISTRY_PATH: docker.pkg.github.com/${{ github.repository }}
          IMAGE_NAME: ubuntu
        run: |
          TAG=`date "+%Y%m%d"`
          docker tag current ${CONTAINER_REGISTRY_PATH}/${IMAGE_NAME}:${TAG}
          docker push ${CONTAINER_REGISTRY_PATH}/${IMAGE_NAME}:${TAG}
          docker tag current ${CONTAINER_REGISTRY_PATH}/${IMAGE_NAME}:latest
          docker push ${CONTAINER_REGISTRY_PATH}/${IMAGE_NAME}:latest
